import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    './src/{index,loader-mdx,bin}.ts',
    './src/{config,next,vite,bun}/index.ts',
    './src/node/loader.ts',
    './src/runtime/next/{index,async}.ts',
    './src/runtime/vite/{browser,server}.ts',
    './src/runtime/shared.ts',
  ],
  format: ['esm', 'cjs'],
  external: [
    'next',
    'typescript',
    'bun',
    '@mdx-js/mdx',
    '@standard-schema/spec',
    'chokidar',
    'esbuild',
    'estree-util-value-to-estree',
    'js-yaml',
    'lru-cache',
    'mdast-util-to-markdown',
    'picocolors',
    'remark-mdx',
    'remark-parse',
    'unified',
    'unist-util-visit',
    'zod',
    'lightningcss',
  ],
  splitting: false,
  clean: true,
  bundle: true,
  noExternal: ['tinyexec', 'picocolors', 'tinyglobby'],
  shims: true,
  dts: true,
  target: 'node18',
});
