import { defineConfig } from 'tsup';

export default defineConfig({
  external: [
    '@tanstack/react-router',
    'waku',
    'react',
    'react-dom',
    'next',
    'tinyexec',
    'orama',
    '@orama/orama',
    '@orama/core',
    'shiki',
    '@shikijs/rehype',
    'zod',
  ],
  dts: true,
  target: 'es2022',
  format: ['esm', 'cjs'],
  entry: [
    'src/{toc,link,breadcrumb,dynamic-link,hide-if-empty}.tsx',
    'src/{source,mdx-plugins,page-tree}/index.ts',
    'src/{negotiation,content}/*',
    'src/source/plugins/lucide-icons.ts',
    'src/source/client.tsx',
    'src/search/{index,client,server,algolia,orama-cloud}.ts',
    'src/utils/use-on-change.ts',
    'src/utils/use-effect-event.ts',
    'src/utils/use-media-query.ts',
    'src/i18n/*.ts',
    'src/highlight/index.ts',
    'src/highlight/client.tsx',
    'src/framework/*',
  ],
});
